[package]
name = "lib_jsh"
version = "0.1.0"
authors = ["Sumeet Padavala <spadavala@atlassian.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_yaml = "0.8"
confy = "0.3.1"
nom = "5.0.1"
